### ISSUE TITLE
New video files not picked up immediately.

### ISSUE THREAD

**Issue by MacLemon** [AMD1212/potty-boom-boom#2]
When adding new video files while Potty-Boom-Boom is already playing the new videos do not get picked up into the random selection until I stop and restart the watchdog or fully restart the Raspberry Pi. This is rather unexpected given the nature of the watchdog script. Might there be some kind of filesystem caching killing the bad randomness?
It also seems that sometimes some videos never get picked up at all while others end up in heavy rotation.

**Comment by KampfCaspar** [comment]
A common issue with 'random' selection... Even 20x the same song would be 'random' - but definitely unwanted.  Therefore I usually suggest a deviation from randomness:
1. read complete list of entries
2. shuffle list
3. play the list _in order_ (no randomness here!!)
4. goto 1 (re-read list for additions/deletions)

A further correction of 'unwanted' random results would be to exclude immediate repetitions between runs:

2a. If first list entry happens to be the same as the previous last one -> discard.

**Comment by KampfCaspar** [comment]
#3

**Comment by AMD1212** [comment]
Closed by merging the pull-request #3.
Thanks a lot for improving the random by de-ranomize the random (-;
